---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meetupapp-webserver
spec:
  replicas: 1
  strategy:
    type: {{ .releaseStrategy }}
  template:
    metadata:
      labels:
        app: meetupapp-webserver
        environment: {{ .environment }}
    spec:
      containers:
        - image: k8s.gcr.io/nginx:{{ .version }}
          name: nginx
          ports:
          - containerPort: {{ .apiPort }}
