---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meetupapp
spec:
  replicas: 1
  strategy:
  # This will be replaced by "RollingUpdate" for prod variables
    type: {{ .releaseStrategy }}
  template:
    metadata:
      labels:
        app: meetupapp
        # This will be replaced by "prod" for prod variables
        environment: {{ .environment }}
    spec:
      containers:
      # This will be extended and replaced by "1.7.9" for prod variables
        - image: k8s.gcr.io/nginx:{{ .version }}
          name: nginx
          ports:
          # This will be replaced by "80" for prod variables
          - containerPort: {{ .apiPort }}
