---
context: docker-desktop
include:
  # By default resource sets are included from a folder with the same
  # name as the resource set's name
  # Variables for the webserver which is in a subfolder of app
  - name: app/webserver
    values:
      version: 1.7.9
      environment: dev
      apiPort: 80
      releaseStrategy: Recreate
  # Variables for the database which is in a different folder
  - name: db
    values:
      servicePort: 5432
      storage: 5Gi
      apiPort: 80
      releaseStrategy: Recreate
      dbImage: 9.6.2-alpine
      pgUser: Boon
      pgDB: docker_tab
      pgPw: whale